# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ce3c57575c7ad0b1a16b31ada79d564cb617b341b1a2f9378d6269f50c7db302f4fbde86cd8b41475e1e5b169106901fbc818eb0351d203eda3d33bcb8fb46e

test:
  secret_key_base: b332db8abd711d6a7f33674281177107638359b97c2fa4847d9401940aee048e705b9ddf2f681e6c40a9ffeff42b54e875a7da8a27c2ad66da8db8e6dba85d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
